# Generated by Django 4.2.7 on 2024-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_chatroom_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
