# Generated by Django 4.2.7 on 2024-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_notes_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
