# Generated by Django 4.2.7 on 2024-03-26 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_option_question_quiz_quiztaker_useranswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_taker',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
