# Generated by Django 4.2.7 on 2024-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
